### ISSUE TITLE
Add "hs-lpn.jpg" (under "Generating computer programs from specifications")

### ISSUE THREAD

**Issue by void-elf** [AI-metrics/master_text#19]
The notebook is trying to display an image named hs-lpn.jpg in that section, but it's broken because the image was not ever pushed to the repo.

![selection_013](https://user-images.githubusercontent.com/4513790/26942858-76abbcea-4c38-11e7-985c-2adf406d0579.png)

**Comment by pde** [comment]
Should be fixed now.
