### ISSUE TITLE
Visualize progress across multiple datasets

### ISSUE THREAD

**Issue by breandan** [AI-metrics/master_text#34]
[This repository](https://github.com/syhw/wer_are_we) tracks WER over several popular speech datasets (including LibriSpeech, WSJ, CHIME) . The [speech recognition section](https://www.eff.org/files/AI-progress-metrics.html#Speech-recognition) (and possibly others) could utilize a [multi-line graph](https://stackoverflow.com/a/13238441) for comparison, with table of a results beneath, possibly something similar to the following chart (taken from [A Historical Perspective of Speech Recognition](http://kk.org/mt-files/reCCearch-mt/(2014)%20A%20historical%20perspective%20of%20speech%20recognition.pdf)):

![Speech progress over time](https://svds.com/wp-content/uploads/2017/03/Screen-Shot-2017-03-21-at-10.59.56-AM-768x500.png)

@jackclarksf @syhw @xdh168

**Comment by pde** [comment]
Ahh, yes, it would be great to incorporate that data. We'll need a little more code to have the metrics share a single graph but it shouldn't be too bad.

@breandan @syhw if you find you're updating the WER are We? source data a lot, it might be worth writing a scraper like the [one we have](https://paste.debian.net/972531/) for the "Are We There Yet?" data. But if updates are only occasional, it'll probably be easiest to do manual transcription. I'm guessing the latter?

**Comment by syhw** [comment]
It is not updated often but I strive to track SOTA, I review and merge PR
if you send some. Parsing
https://raw.githubusercontent.com/syhw/wer_are_we/master/README.md should
be trivial, it'll stay Markdown, datasets names are ### and links are
http.*arxiv.* or http.*pdf

**Comment by pde** [comment]
This is done in at least a minimal, bare-bones fashion. See here for an example of two metrics on a single graph: 

https://www.eff.org/files/AI-progress-metrics.html#Visual-Question-Answering

**Comment by pde** [comment]
@breandan if you want to submit a PR that changes the WER graphs to use this new multiple-metrics-per-graph format, it should be fairly easy to do.

**Comment by pde** [comment]
(I haven't tried it with more than two graphs yet, but passing `keep=True` on all but the last one, and `resue=` (return value of the first call) to all but the first, _should_ work.)
