### ISSUE TITLE
bAbI task 10k are solved, but not 1k

### ISSUE THREAD

**Issue by jaseweston** [AI-metrics/master_text#35]
bAbI tasks are in two flavors: with 1k and 10k training examples.

You write: "The Facebook BABI 20 QA dataset is an example of a basic (and now solved) reading comprehension task."

But this is only true in the 10k case, where memorization plays an important part.
For 1k, which many people have published (in fact the original paper only uses 1k) it is much harder, see e.g. Table 1 of https://arxiv.org/pdf/1606.04582.pdf

So there are still interesting things to try there, which relate to important problems in neural networks:  data efficiency and capacity control, learning compositionality, small-shot learning and task transfer.

**Comment by pde** [comment]
@jaseweston I made a pull request (#38) that tries to sort the data into the 1K and 10K cases. Does that look right to you? As in, there has been essentially no progress with the 1K dataset?

**Comment by jaseweston** [comment]
1K is not solved, but some progress has been made:
N2N  -> 10 failed (2015)
QRN -> 5 failed  (2017)

The text looked ok though because you didn't say "essentially no progress"
as far as I can see? (other than in the email to me)

**Comment by pde** [comment]
Ahh, I must be missing something in my reading of [your original paper](https://arxiv.org/abs/1502.05698). Table 3 seems to show that MemNN+AM+NG+NL with 1k training examples scored 93% and 4 failed, which seems better than QRN with 1k training examples (90.1% and 5 failed, though with different numbers of layers in those models)?

**Comment by pde** [comment]
![Weston 2015 (MemNN+) Table 3](https://user-images.githubusercontent.com/479213/27448719-a4296958-573a-11e7-8cf5-50c5c4032de4.png)

![Seo 2017 (QRNs) Table1](https://user-images.githubusercontent.com/479213/27448748-bd2a90bc-573a-11e7-8daa-6e828a6a0d40.png)

**Comment by jaseweston** [comment]
Yes, the original paper uses Supporting Facts during training, not
comparable.

**Comment by pde** [comment]
OK, we've added a way to show that some data points are not literally comparable, but still including them on graphs for interest, and used that for the original paper's MemNN result.

**Comment by jaseweston** [comment]
Thanks!
