### ISSUE TITLE
Missing language modeling results

### ISSUE THREAD

**Issue by syhw** [AI-metrics/master_text#36]
https://www.microsoft.com/en-us/research/wp-content/uploads/2012/07/rnn_ctxt_TR.sav_.pdf got 74.1 PPL on PTB with RNN-LDA+KN5+cache in 2012.
Also, you should include a KN5 baseline in PTB PPL. Ensemble of RNN-LDA LMs at 80.1 PPL.

Probably you should include the billion word corpus for LM results, as it is less "overfitted" as a dataset than PTB, and as it is bigger it is better suited for RNN/LSTM methods.

**Comment by pde** [comment]
@syhw this is done and live. Let us know if we missed anything!
