### ISSUE TITLE
Add all the interesting Atari games

### ISSUE THREAD

**Issue by pde** [AI-metrics/master_text#4]
There are lots; we should add all the ones that have 3+ reports in the literature or which appear to be interesting for some conceptual reason.

**Comment by pde** [comment]
It may be possible to parse each of the large tables that's in the interesting papers about these games, rather than doing manual entry for all of them?

**Comment by void-elf** [comment]
I've added all the games which have been popular in AI research, but for future reference we're far from having all the Atari games: https://en.wikipedia.org/wiki/List_of_Atari_2600_games#Games_published_by_Atari_and_Sears (see this section and the next for games made by 3rd parties).
