### ISSUE TITLE
Import or scrape data from WER_are_we

### ISSUE THREAD

**Issue by pde** [AI-metrics/master_text#42]
Making this as a sub issue of #34. This repo has great Word Error Rate data for speech recognition tasks:

https://raw.githubusercontent.com/syhw/wer_are_we/master/README.md

Proposed scraper plan: https://github.com/AI-metrics/AI-metrics/issues/34#issuecomment-310025224

Relatedly, we should decide on whether scrapers keep living in the Notebook or maybe want to live as separate scripts on disk. My instinct is probably the latter (and we should move the awty scraper too...)

**Comment by void-elf** [comment]
@syhw would you be open to PR that standardizes how dates are formatted on your project (https://github.com/syhw/wer_are_we)? I'm happy to submit one, as it'll save me quite a bit of work on the scraper I'm writing to get your data.

**Comment by syhw** [comment]
Sure, go ahead. 👍

**Comment by pde** [comment]
Nice work @ynasser !
