### ISSUE TITLE
Make a metric.table!

### ISSUE THREAD

**Issue by void-elf** [AI-metrics/master_text#44]
... in bottom right corner, includes a "edit on github" button.

As a last resort, use: `from IPython.display import html`.

**Comment by pde** [comment]
Let's use [this branch](https://github.com/AI-metrics/AI-metrics/tree/editable-data) for this.

**Comment by pde** [comment]
In it, the `Metric` class is in `taxonomy.py`, so you should be able to more sensibly add methods to it there.

**Comment by void-elf** [comment]
What was the scope of this issue again? Was it just displaying a nice table based on the measurements for that specific metric (and if so, why isn't this part of #46)?

And what were we going to do with the "edit on github" button? I vaguely remember something about letting users modify the data via CSVs.


Also, how does this table look:


![selection_028](https://user-images.githubusercontent.com/4513790/27711184-2f0b522e-5cd7-11e7-8aa1-4d4542fefaec.png)

**Comment by pde** [comment]
1. It wasn't part of #46 because it predates #46. I'm still resisting using JSON+JavaScript for all of our data display, but I can maybe be talked into it.
2. The table is the nice way we show all the results now that the raw data is being moved into [separate python files](https://github.com/AI-metrics/AI-metrics/tree/editable-data/data), which can be edited in a nice way [with links like this](https://github.com/AI-metrics/AI-metrics/edit/editable-data/data/vision.py)
3. Your table above looks like a good start! Will make a slightly more polished example here in a sec

**Comment by pde** [comment]
Here's what I imagine this looking like:

| Date        | Algorithm           |  Result | Paper  |
| ------------- |:-------------:|:-----:|:------
| 2015-06-10| Attentive Reader | 63.0 | [Teaching Machines to Read and Comprehend](https://arxiv.org/abs/1506.03340)
| 2015-06-10| Impatient Reader | 63.8 | [Teaching Machines to Read and Comprehend](https://arxiv.org/abs/1506.03340)
| 2015-06-10| AIA | 63.8 | [Iterative Alternating Neural Attention for Machine Reading](https://arxiv.org/abs/1606.02245v4)
| ... | ...     |  ...|...

`                                                   `[edit this data on Github](https://github.com/AI-metrics/AI-metrics/edit/editable-data/data/reading_comprehension.py)

**Comment by pde** [comment]
(except the "edit this data on github" link would be smaller and right-aligned?

I'm wondering whether to 
1. use the Papername as a hyperlink, as shown above; or
2. have a separate paper name and URL; or
3. Papername as hyperlink plus the explicit arXiv paper ID, where applicable, since those are sometimes useful

**Comment by void-elf** [comment]
I will stick to #1 (papername as hyperlink). I don't think adding the arxiv ID (pictured below) is all that helpful or nice to look at:

| Date        | Algorithm           |  Result | Paper  |
| ------------- |:-------------:|:-----:|:------
| 2015-06-10| Attentive Reader | 63.0 | [Teaching Machines to Read and Comprehend (arxiv ID: 1506.03340)](https://arxiv.org/abs/1506.03340)
| 2015-06-10| Impatient Reader | 63.8 | [Teaching Machines to Read and Comprehend (arxiv ID: 1506.03340)](https://arxiv.org/abs/1506.03340)
| 2015-06-10| Impatient Reader | 63.8 | [Teaching Machines to Read and Comprehend (arxiv ID: 1506.03340)](https://arxiv.org/abs/1506.03340)
| zebra stripes | are neat      |    $1 |

**Comment by pde** [comment]
In some cases we'll want to add ± on the result (if `min_val` / `max_val` are not the same as the result) . Not sure how best to represent date ranges, either writing out the full range or just adding a *

**Comment by pde** [comment]
There are probably more columns we'll want to add either now or in the future. For instance links to source code (which currently are occasionally in the `replicated` field), or any notes that may be attached to the `Measurement` object.

**Comment by pde** [comment]
But let's not worry about those immediately.

**Comment by void-elf** [comment]
@pde So, I'm done making tables. For the "Edit me on GitHub" link, I've noticed that not all the data has been moved into the `/data` directory. Are you working on moving it, should I do it, or should I just skip anything that hasn't been moved for now?

**Comment by void-elf** [comment]
> I'm still resisting using JSON+JavaScript for all of our data display, but I can maybe be talked into it.

One advantage of using JSON or CSV files for storing data is that if people already have data lying around that they want to give us, it'll already be in a usable format. What we have now is very, very unusual by data analysis project standards and might scare people away (and requires them to know Python if they want to submit a PR, instead of a much more widespread data representation language).

**Comment by void-elf** [comment]
Most recent commits on this: https://github.com/AI-metrics/AI-metrics/commit/136152fe9e88b3255b11738d856b4716c57a55b1

Here's what the table looks like right now:
![selection_029](https://user-images.githubusercontent.com/4513790/27715451-17e79228-5cec-11e7-9900-b03b60dd9595.png)

Right-aligning the `<p>` element is mysteriously not working, but perhaps that's for the best, as the "Edit me" link won't accidentally visually blend into all the other links in the right column and more people are likely to see it.

edit: also right now the default "Edit me" link leads to the github page. I still need to edit the `data_url` field on all the metrics, but I need https://github.com/AI-metrics/AI-metrics/issues/44#issuecomment-312130712 answered.

**Comment by pde** [comment]
Looks good in general! Obviously the computer chess/wikipedia case is a little weird but we can worry about that later...

**Comment by pde** [comment]
Maybe the column title should be **Paper / Source** for now

**Comment by void-elf** [comment]
I can't seem to get the table to render unless in each cell I explicitly include:
```
from IPython.display import HTML
HTML(metric_name.table())
```

I tried refactoring it into the `table` function with no luck. This seems less than ideal, as we'd have to include this in every cell we wanted tables to be displayed in. Can someone think of a more efficient way?
