### ISSUE TITLE
Broken export of progress.json

### ISSUE THREAD

**Issue by jamesscottbrown** [AI-metrics/master_text#67]
The ``export_json`` function in [AI-progress-metrics.ipynb](https://github.com/AI-metrics/AI-metrics/blob/3620518b90609df1456b6c3ef9ad597958e1ca41/AI-progress-metrics.ipynb) contains the line:

``problem_data[problem_attr] = map(lambda x: x.name, getattr(problem, problem_attr))``

However, in Python 3 the ``map`` function returns a map object rather than a list, so the mostly recently commited [``progress.jspn``](https://github.com/AI-metrics/AI-metrics/blob/master/export-api/v01/progress.json) contains unhelpul things like:

            "subproblems": "<map object at 0x7faccf3be4a8>",
            "superproblems": "<map object at 0x7faccf3bec50>",

To fix this, the line should be changed to:

``problem_data[problem_attr] = list(map(lambda x: x.name, getattr(problem, problem_attr)))``

**Comment by pde** [comment]
Hi! I've made that change to git master, and pushed a new export. Out of curiosity, why file a bug report with the code change rather than sending a pull request?

**Comment by jamesscottbrown** [comment]
Mostly because the code is in an ipython notebook and didn't want to deal with configuring merge filters for it, but having just checked the README instructions again I see that it is much simpler that I had thought.
