### ISSUE TITLE
Investigate normalization of scaling for scores in Atari papers

### ISSUE THREAD

**Issue by void-elf** [AI-metrics/master_text#7]
Some of the Atari data we collected had negative game "scores" for games where the scores are always positive, and one paper mentions this: "Since the scale of scores varies greatly from game to game, we
fixed all positive rewards to be 1 and all negative rewards to be −1, leaving 0 rewards unchanged."[1]

We need to make sure the scores we are entering are all normalized in the same way.

[1] Playing Atari with Deep Reinforcement Learning

**Comment by pde** [comment]
If you determine that these metrics are using something normalized rather than raw score, please make a new implementation of the scale interface. It can probably be identical to the `linear = Linear()` one, but with a different `axis_label`.

**Comment by void-elf** [comment]
I’ve looked through all the results to see what forms of reward scoring/normalization they’re using, and they’re all either explicitly using the same as [1] or reference it (when discussing comparison to previous results) in a way that seems to imply that it’s OK to put all these on the same, linear graph.
 
So, I’ve made another metric in e57d0fd4d9c6cf447447d3bbf0e5a9f6a0ac38e1 that’s basically the same as Linear (named AtariLinear), as was suggested above, to make it more clear that we’re not using raw scores here.
